language: node_js
node_js:
  - "12"

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - npm install -g grunt-cli

install:
  - npm install
  - npm rebuild node-sass

cache:
  directories:
    - node_modules

script:
  - npm run generate
